apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-service
  template:
    metadata:
      labels:
        app: tracking-service
    spec:
      containers:
      - name: tracking-service
        image: tubestahap2-tracking-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084